modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mpnlink"
version="1.0.0"
displayName="MPN Link Mod"
authors="MPN"
description="MPN Link Mod for Discord Verification"

[[dependencies.mpnlink]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"
